### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/soar-cli-documentation#3]
Is this a backup of the google code or GitHub wikis from somewhere? Or is it generated? And how is it used? Does it feed into a generated website anywhere?

If it's obsolete, then I will archive it.

**Comment by scijones** [comment]
If I look at the Soar manual for some of these commands, they are word-for-word the same. I wonder if this fed into generating the manual.

**Comment by garfieldnate** [comment]
The manual is including these by downloading from the Soar repository wiki. Maybe these were the original source for that wiki?

**Comment by garfieldnate** [comment]
This hasn't been touched in 9 years, and the Wiki is what's used to build the manual; the Wiki hasn't been touched in 5 years, either, and a newer source of truth will be the new documentation repository. Still unclear to me whether we also need to pull this text into Soar's source code for the various help commands.
